### ISSUE TITLE
asp.net core 2.2

### ISSUE THREAD

**Issue by kvroeden** [MultiTenancyServer/MultiTenancyServer.Samples#1]
Hi,

This doesn't seem to work on net core 2.2 (in combination with Sql Server, haven't tested SQLite). The error I get is: "Failed to convert parameter value from a ApplicationDbContext to a Int64.". The inner exception reads: "System.InvalidCastException: Object must implement IConvertible.". It happens in SeedData line 78
`var alice = userMgr.FindByNameAsync("alice@contoso.com").Result;`
of the "int64AspNetIdentityAndEfCore" sample project. 

To reproduce convert the sample project to net core 2.2 and change the connection string for example
`"Server=(localdb)\\mssqllocaldb;Database=test;Trusted_Connection=True;MultipleActiveResultSets=true"`
you also need to add Id=1 etc when creating the Tenants.

I have the same sort of error when I use`GUID` instead of `long` when defining the Key of ApplicationUser, ApplicationRole and ApplicationTenant

Thanks

**Comment by krispenner** [comment]
Hi @kvroeden,

A change was made in EF Core 2.1 (from 2.0) in how Global Query Filters were invoked which was causing the issue you are reporting. Today I updated all code to the latest versions available. You will see the sample projects are also updated.

### NuGet packages
MultiTenancyServer **1.2.0** targets: .NET Core 2.2, ASP.NET 2.2 and EF Core 2.2
MultiTenancyServer **1.1.0** targets: .NET Core 2.1, ASP.NET 2.1 and EF Core 2.1
MultiTenancyServer **0.9.0** targets: .NET Core 2.0, ASP.NET 2.0 and EF Core 2.0

### Breaking Changes
The key breaking change you will need to make is in your DbContext class.

Remove the _tenantId private helper property:
```
// Use a property wrapper to access the scoped tenant on demand.
private object _tenantId => _tenancyContext?.Tenant?.Id;
```

Replace all lines similar to:
`b.HasTenancy(() => _tenantId, _tenancyModelState, hasIndex: false);`
With:
`b.HasTenancy(() => _tenancyContext.Tenant.Id, _tenancyModelState, hasIndex: false);`

In SaveChanges(), replace:
`this.EnsureTenancy(_tenantId, _tenancyModelState, _logger);`
With:
`this.EnsureTenancy(_tenancyContext?.Tenant?.Id, _tenancyModelState, _logger);`

Let me know if that works for ya now.
Cheers

**Comment by kvroeden** [comment]
Hi Kris,

Everything is working fine now (ASP.NET Core 2.2 & Azure Sql Server) 
Thanks for your quick response.

Cheers,
Keesjan
