### ISSUE TITLE
I can't make the demo to work 

### ISSUE THREAD

**Issue by jkrus2930** [MultiTenancyServer/MultiTenancyServer.Samples#2]
Hello, 

I followed the instructions and run the demo project. I want to try MultiTenancy Server With AspNet Identity And EFCore. The project show up an exception:

![2019-03-28_025006](https://user-images.githubusercontent.com/43524565/55120113-b2ebe080-5105-11e9-8c80-cf3882742ac3.png)

I want to implement it in a real project and really need help. Thanks.

**Comment by krispenner** [comment]
Either the `_signInManager` field is null or the `model` parameter is null.
You will need to investigate why this is, adding a break-point on that line while debugging will tell you.

**Comment by jkrus2930** [comment]
Thanks for your answer. The example is running very well.  My problem now is implementing the MultitenancyServer in my project.  

I am using Asp.Net Core 2.2, EF core 2.2, Asp Identity and Angular as Front-end. I followed the steps in the example and in the Read.Me file. But is not working. I think the problem is with the route configuration. 

How should I configure the route if I use Angular as front-end ?

In my startup file I have: 
`app.UseMvc(routes =>
      {
        routes.MapSpaFallbackRoute(
          name: "spa-fallback",
          defaults: new { controller = "Fallback", action = "Index" }
        );
      });`

and my FallBack class: 

`public class Fallback : Controller 
    {
        public IActionResult Index()
        {
            return PhysicalFile(Path.Combine(Directory.GetCurrentDirectory(),
            "wwwroot", "index.html"), "text/HTML");
        }
    }`

I am using VS Code and for debug I use the command `dotnet watch run`. 

Any help please.

**Comment by krispenner** [comment]
Hi @jkrus2930 I am very sorry for not replying, too busy with work and then I just totally forgot.
I assume you either resolved this yourself or moved onto something else instead of this.
I'll close this, but feel free to open it if you would still like to step through it. However, I am not familiar at all with Angular.
