### ISSUE TITLE
Questions about the sample projects

### ISSUE THREAD

**Issue by DavidDury** [MultiTenancyServer/MultiTenancyServer.Samples#3]
Ihave 2 questions about the samples:

1. the sample project that is using the IdentityServer 4, it's purpose is to secure API endpoints?
2. the difference between AspNetIdentityAndEFCore and Int64AspNetIdentityAndEFCore is just to define the primary key type as long ( public class ApplicationUser : IdentityUser<long>) ?

**Comment by krispenner** [comment]
Sorry for replying so late.
1. Yes that is correct.
2. Yes that is also correct, some people asked for how to use `Int64 `for the IDs instead of `String`.
