### ISSUE TITLE
DatabasePerTenantAspIdAndEF Sample

### ISSUE THREAD

**Issue by ghost** [MultiTenancyServer/MultiTenancyServer.Samples#4]
Any chance you can provide a sample for Sample project: DatabasePerTenantAspIdAndEF? It would be much appreciated!

**Comment by krispenner** [comment]
Hi @marlonlaan, sorry for the late reply. This is available for v1, I just never got to upgrading it to my v2 beta yet.

Project:
https://github.com/MultiTenancyServer/MultiTenancyServer.Samples/tree/v1/src/DatabasePerTenantAspIdAndEF

And specifically this file is the key piece:
https://github.com/MultiTenancyServer/MultiTenancyServer.Samples/blob/v1/src/DatabasePerTenantAspIdAndEF/Data/Application/ApplicationDbContextConfigurator.cs
